####
# Deploys the ingress controller as a daemon set, then creates the external ELB to serve it traffic
###
apiVersion: extensions/v1beta1
kind: DaemonSet
# kind: Deployment
metadata:
  name: k8s-routers
  labels:
    app: k8s-routers
spec:
  # replicas: 1
  template:
    metadata:
      labels:
        app: k8s-routers
    spec:
      containers:
      - image: registry-1.docker.io/whitlockjc/k8s-pods-ingress:v0
        imagePullPolicy: Always
        name: k8s-public-router
        ports:
          - containerPort: 80
            hostPort: 80
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # Use the configuration to use the public/private paradigm (public version)
          - name: API_KEY_SECRET_LOCATION
            value: routing:public-api-key
          - name: HOSTS_ANNOTATION
            value: publicHosts
          - name: PATHS_ANNOTATION
            value: publicPaths
      - image: registry-1.docker.io/whitlockjc/k8s-pods-ingress:v0
        imagePullPolicy: Always
        name: k8s-private-router
        ports:
          - containerPort: 81
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # Use the configuration to use the public/private paradigm (private version)
          - name: API_KEY_SECRET_LOCATION
            # Use the same key for internal and external since the SSO Proxy does not know how to inject the proper private API Key upon redirect
            value: routing:public-api-key
            # value: routing:private-api-key
          - name: HOSTS_ANNOTATION
            value: privateHosts
          - name: PATHS_ANNOTATION
            value: privatePaths
          # Since we cannot have two containers listening on the same port, use a different port for the private router
          - name: PORT
            value: "81"
